import test from "node:test";
import assert from "node:assert/strict";
import * as XLSX from "xlsx";
import { reportGenerator } from "./reportGenerator.js";

const GENERATED_AT = new Date("2026-05-06T00:00:00.000Z");

const EXPECTED_PDF_ATTENDANCE_COLUMNS = [
  { header: "Employee", width: 26, halign: "left" },
  { header: "Role/Division", width: 20, halign: "left" },
  { header: "Attendance Coverage", width: 22, halign: "center" },
  { header: "On Time", width: 11, halign: "center" },
  { header: "Late", width: 11, halign: "center" },
  { header: "Alpha", width: 11, halign: "center" },
  { header: "Work Mode Mix", width: 28, halign: "center" },
  { header: "Latest Status", width: 18, halign: "center" },
  { header: "Notes", width: 31, halign: "left" },
];

const COMPLETE_SUMMARY_DATA = {
  summary: {
    total_ontime: 5,
    total_late: 1,
    total_alpha: 0,
    total_wfo: 3,
    total_wfh: 1,
    total_wfa: 1,
  },
  analytics: {
    discipline_analysis: {
      average_discipline_score: 88,
    },
  },
  report: {
    data: [
      {
        full_name: "Rina Detail",
        nip_nim: "123456",
        role: "Staff",
        email: "rina@example.com",
        phone_number: "08123456789",
        attendance_date: "2026-05-01",
        time_in: "08:00",
        time_out: "17:00",
        work_hour: "09:00",
        status: "ontime",
        information: "wfo",
        notes: "Hadir tepat waktu",
        discipline_score: 88,
        discipline_label: "Excellent",
        location_details: {
          category: "wfo",
          description: "Kantor Palu",
        },
      },
    ],
    user_attendance_summary: [
      {
        full_name: "Rina Summary",
        role_name: "Staff",
        division: "Operations",
        expected_working_days: 10,
        valid_attendance_days: 10,
        attendance_coverage_label: "10/10",
        on_time_days: 8,
        late_days: 2,
        alpha_days: 0,
        wfo_days: 6,
        wfh_days: 2,
        wfa_days: 2,
        latest_attendance_status: "ontime",
        latest_attendance_date: "2026-05-01",
        summary_note: "Attendance coverage confirmed by backend.",
      },
    ],
    pagination: {
      total_records: 1,
    },
  },
};

function getSheetValue(sheet, cellAddress) {
  return sheet[cellAddress]?.v;
}

test("report generator marks missing summary counts as unavailable instead of factual zeroes", () => {
  const rows = reportGenerator.buildSummaryRows({
    total_ontime: 2,
    total_late: 1,
  });

  assert.deepEqual(rows, [
    ["On Time", "2"],
    ["Late", "1"],
    ["Alpha (Absent)", "Unavailable"],
    ["Work From Office", "Unavailable"],
    ["Work From Home", "Unavailable"],
    ["Work From Anywhere", "Unavailable"],
  ]);
});

test("report generator keeps explicit zero summary counts as zero", () => {
  const rows = reportGenerator.buildSummaryRows({
    total_ontime: 0,
    total_late: 0,
    total_alpha: 0,
    total_wfo: 0,
    total_wfh: 0,
    total_wfa: 0,
  });

  assert.deepEqual(rows, [
    ["On Time", "0"],
    ["Late", "0"],
    ["Alpha (Absent)", "0"],
    ["Work From Office", "0"],
    ["Work From Home", "0"],
    ["Work From Anywhere", "0"],
  ]);
});

test("report generator builds PDF metadata rows from /summary report/export period totals", () => {
  const rows = reportGenerator.buildPdfMetadataRows(
    COMPLETE_SUMMARY_DATA.report,
    "monthly",
    GENERATED_AT,
  );

  assert.deepEqual(rows, [
    ["Period", "Monthly"],
    ["Generated on", reportGenerator.formatGeneratedOn(GENERATED_AT)],
    ["Total Records", "1"],
    [
      "Provenance",
      "Client-generated from /summary using the selected report/export period. Missing backend fields remain Unavailable.",
    ],
  ]);
});

test("report generator builds compact PDF header metadata rows for the branded export header", () => {
  const rows = reportGenerator.buildPdfHeaderMetadataRows(
    "monthly",
    GENERATED_AT,
  );

  assert.deepEqual(rows, [
    ["Period", "Monthly"],
    ["Generated on", reportGenerator.formatGeneratedOnCompact(GENERATED_AT)],
    ["Generated by", "Infinite Track System"],
    ["Data source", "/summary payload for selected report/export period"],
  ]);
});

test("report generator builds PDF footer content with page provenance", () => {
  assert.deepEqual(reportGenerator.buildPdfFooterContent(2, 5), {
    left: "Generated by Infinite Track System",
    center: "Page 2",
    right: "Confidential internal report",
  });
});

test("report generator builds executive summary cards from explicit backend counts and analytics", () => {
  const cards = reportGenerator.buildExecutiveSummaryCards(
    COMPLETE_SUMMARY_DATA.summary,
    COMPLETE_SUMMARY_DATA.report.data,
    COMPLETE_SUMMARY_DATA.analytics,
  );

  assert.deepEqual(cards, [
    {
      label: "Attendance Rate",
      value: "100%",
      caption: "6 present of 6 explicit rows.",
      state: "ready",
      accent: [139, 92, 246],
    },
    {
      label: "Late / Alpha Risk",
      value: "1",
      caption: "16,7% of rows need status review.",
      state: "ready",
      accent: [245, 158, 11],
    },
    {
      label: "Avg Discipline",
      value: "88",
      caption: "Explicit backend average discipline score.",
      state: "ready",
      accent: [6, 182, 212],
    },
    {
      label: "Needs Attention",
      value: "Unavailable",
      caption: "Field is not present in the canonical backend response.",
      state: "backendRequired",
      accent: [236, 72, 153],
    },
  ]);
});

test("report generator builds executive KPI helper output from summary/report sections", () => {
  assert.deepEqual(
    reportGenerator.buildExecutiveKpiCards(COMPLETE_SUMMARY_DATA),
    reportGenerator.buildExecutiveSummaryCards(
      COMPLETE_SUMMARY_DATA.summary,
      COMPLETE_SUMMARY_DATA.report.data,
      COMPLETE_SUMMARY_DATA.analytics,
    ),
  );
});

test("report generator keeps executive summary cards conservative when backend counts or analytics are incomplete", () => {
  const cards = reportGenerator.buildExecutiveSummaryCards(
    {
      total_ontime: 2,
      total_late: 1,
    },
    [
      { full_name: "Explicit Score", discipline_score: 88 },
      { full_name: "Missing Score" },
    ],
  );

  assert.equal(cards[0].state, "needsData");
  assert.equal(cards[0].value, "Unavailable");
  assert.equal(cards[1].state, "needsData");
  assert.equal(cards[2].state, "backendRequired");
  assert.equal(cards[2].value, "Unavailable");
  assert.equal(
    cards[2].caption,
    "Explicit backend average discipline score is not present in the canonical response.",
  );
  assert.equal(cards[3].state, "backendRequired");
});

test("report generator builds attendance distribution as a donut from explicit backend counts", () => {
  assert.deepEqual(
    reportGenerator.buildAttendanceDistribution(COMPLETE_SUMMARY_DATA.summary),
    {
      title: "Attendance Status Distribution",
      state: "ready",
      chartType: "donut",
      note: "Explicit counts from selected-period summary.",
      total: 6,
      segments: [
        {
          label: "On Time",
          value: 5,
          color: [139, 92, 246],
          percentage: 83.33333333333334,
          percentageLabel: "83,3%",
        },
        {
          label: "Late",
          value: 1,
          color: [245, 158, 11],
          percentage: 16.666666666666664,
          percentageLabel: "16,7%",
        },
        {
          label: "Alpha",
          value: 0,
          color: [236, 72, 153],
          percentage: 0,
          percentageLabel: "0%",
        },
      ],
    },
  );
});

test("report generator builds work mode distribution from explicit backend counts", () => {
  assert.deepEqual(
    reportGenerator.buildWorkModeDistribution(COMPLETE_SUMMARY_DATA.summary),
    {
      title: "Work Mode Distribution",
      state: "ready",
      chartType: "horizontalBars",
      note: "Explicit counts from selected-period summary.",
      total: 5,
      bars: [
        {
          label: "WFO",
          value: 3,
          color: [139, 92, 246],
          percentage: 60,
          percentageLabel: "60%",
        },
        {
          label: "WFH",
          value: 1,
          color: [6, 182, 212],
          percentage: 20,
          percentageLabel: "20%",
        },
        {
          label: "WFA",
          value: 1,
          color: [245, 158, 11],
          percentage: 20,
          percentageLabel: "20%",
        },
      ],
    },
  );
});

test("report generator builds discipline score ranges from explicit row scores", () => {
  assert.deepEqual(
    reportGenerator.buildDisciplineScoreDistribution([
      { discipline_score: 55 },
      { discipline_score: 72 },
      { discipline_score: 88 },
    ]),
    {
      title: "Discipline Score Range",
      state: "ready",
      chartType: "horizontalBars",
      note: "Binned from 3 explicit row scores.",
      total: 3,
      bars: [
        {
          label: "Excellent (85-100)",
          value: 1,
          color: [139, 92, 246],
          percentage: 33.33333333333333,
          percentageLabel: "33,3%",
        },
        {
          label: "Good (70-84)",
          value: 1,
          color: [6, 182, 212],
          percentage: 33.33333333333333,
          percentageLabel: "33,3%",
        },
        {
          label: "Needs Review (50-69)",
          value: 1,
          color: [245, 158, 11],
          percentage: 33.33333333333333,
          percentageLabel: "33,3%",
        },
        {
          label: "Attention (<50)",
          value: 0,
          color: [236, 72, 153],
          percentage: 0,
          percentageLabel: "0%",
        },
      ],
    },
  );
});

test("report generator builds ready statistics cards from explicit summary counts and discipline rows", () => {
  const cards = reportGenerator.buildPdfStatisticsCards(
    COMPLETE_SUMMARY_DATA.summary,
    [
      { discipline_score: 55 },
      { discipline_score: 72 },
      { discipline_score: 88 },
    ],
  );

  assert.deepEqual(cards, [
    reportGenerator.buildAttendanceDistribution(COMPLETE_SUMMARY_DATA.summary),
    reportGenerator.buildWorkModeDistribution(COMPLETE_SUMMARY_DATA.summary),
    reportGenerator.buildDisciplineScoreDistribution([
      { discipline_score: 55 },
      { discipline_score: 72 },
      { discipline_score: 88 },
    ]),
  ]);
});

test("report generator keeps statistics cards honest when backend counts or discipline ranges are incomplete", () => {
  const cards = reportGenerator.buildPdfStatisticsCards(
    {
      total_ontime: 2,
      total_late: 1,
      total_wfo: 1,
    },
    [{ discipline_score: 88 }, { full_name: "Missing Score" }],
  );

  assert.equal(cards[0].state, "needsData");
  assert.equal(
    cards[0].message,
    "Explicit on-time, late, and alpha counts are unavailable.",
  );
  assert.equal(cards[1].state, "needsData");
  assert.equal(
    cards[1].message,
    "Explicit WFO, WFH, and WFA counts are unavailable.",
  );
  assert.equal(cards[2].state, "needsData");
  assert.equal(
    cards[2].message,
    "Some backend rows do not provide explicit 0-100 discipline scores.",
  );
});

test("report generator exposes PDF attendance table columns for the branded export layout", () => {
  assert.deepEqual(
    reportGenerator.buildPdfAttendanceTableColumns(),
    EXPECTED_PDF_ATTENDANCE_COLUMNS,
  );
});

test("report generator builds truthful PDF attendance summary rows from backend user summaries", () => {
  assert.deepEqual(
    reportGenerator.buildPdfAttendanceTableRows([
      {
        full_name: "Custom Person 77",
        role_name: "Supervisor",
        division: "Finance",
        expected_working_days: 10,
        valid_attendance_days: 10,
        attendance_coverage_label: "10/10",
        on_time_days: 0,
        late_days: 2,
        alpha_days: 0,
        wfo_days: 0,
        wfh_days: 1,
        wfa_days: 0,
        latest_attendance_status: "alpha",
        latest_attendance_date: "2026-05-03",
        summary_note: "Backend-verified coverage.",
      },
    ]),
    [
      [
        "Custom Person 77",
        "Supervisor / Finance",
        "10/10",
        "0",
        "2",
        "0",
        "WFO 0 • WFH 1 • WFA 0",
        "Alpha",
        `Backend-verified coverage. Latest attendance: ${reportGenerator.formatDateValue("2026-05-03")}.`,
      ],
    ],
  );
});

test("report generator preserves truthful summary notes when backend omits expected working days", () => {
  const [row] = reportGenerator.buildPdfAttendanceTableRows([
    {
      full_name: "Missing Expected Days",
      role_name: "Staff",
      division: "HR",
      attendance_coverage_label: "Unavailable",
      on_time_days: 4,
      late_days: 0,
      alpha_days: 0,
      wfo_days: 2,
      wfh_days: 2,
      wfa_days: 0,
      latest_attendance_status: "ontime",
      latest_attendance_date: "2026-05-04",
      expected_working_days: null,
      summary_note: "Backend did not expose expected workdays.",
    },
  ]);

  assert.equal(row[0], "Missing Expected Days");
  assert.equal(row[2], "Unavailable");
  assert.equal(row[3], "4");
  assert.equal(row[5], "0");
  assert.equal(row[7], "On Time");
  assert.match(row[8], /Backend did not expose expected workdays\./);
  assert.match(row[8], /Expected working days unavailable\./);
});

test("report generator keeps user attendance summary backend-required when summary rows are absent", () => {
  assert.deepEqual(
    reportGenerator.buildUserAttendanceSummaryTableModel({
      data: COMPLETE_SUMMARY_DATA.report.data,
    }),
    {
      state: "backendRequired",
      message:
        "Backend user_attendance_summary is unavailable for the selected period.",
      rows: [
        [
          "Backend Required",
          "Unavailable",
          "Unavailable",
          "Unavailable",
          "Unavailable",
          "Unavailable",
          "Unavailable",
          "Unavailable",
          "Backend user_attendance_summary is unavailable for the selected period.",
        ],
      ],
    },
  );
});

test("report generator returns consistent status badge palettes for PDF pills", () => {
  assert.deepEqual(reportGenerator.getStatusBadgeStyle("On Time"), {
    fillColor: [220, 252, 231],
    textColor: [21, 128, 61],
    borderColor: [134, 239, 172],
  });
  assert.deepEqual(reportGenerator.getStatusBadgeStyle("late"), {
    fillColor: [255, 237, 213],
    textColor: [194, 65, 12],
    borderColor: [253, 186, 116],
  });
  assert.deepEqual(reportGenerator.getStatusBadgeStyle("mystery"), {
    fillColor: [241, 245, 249],
    textColor: [100, 116, 139],
    borderColor: [203, 213, 225],
  });
});

test("report generator returns consistent work mode badge palettes for PDF pills", () => {
  assert.deepEqual(reportGenerator.getWorkModeBadgeStyle("wfo"), {
    fillColor: [245, 243, 255],
    textColor: [109, 40, 217],
    borderColor: [196, 181, 253],
  });
  assert.deepEqual(reportGenerator.getWorkModeBadgeStyle("Work From Home"), {
    fillColor: [236, 254, 255],
    textColor: [14, 116, 144],
    borderColor: [165, 243, 252],
  });
  assert.deepEqual(reportGenerator.getWorkModeBadgeStyle("Unknown"), {
    fillColor: [241, 245, 249],
    textColor: [100, 116, 139],
    borderColor: [203, 213, 225],
  });
});

test("report generator builds honest insight copy without inventing missing backend fields", () => {
  const paragraph = reportGenerator.buildHonestInsightParagraph(
    {
      total_ontime: 2,
      total_late: 1,
    },
    {
      pagination: { total_records: 7 },
    },
  );

  assert.match(paragraph, /Total Records at 7/);
  assert.match(paragraph, /Alpha \(Absent\)/);
  assert.match(paragraph, /Work From Office/);
  assert.match(paragraph, /Unavailable/);
  assert.match(paragraph, /does not invent reporting truth/);
});

test("report generator builds a PDF layout model without inventing summary table truth", () => {
  const layoutModel = reportGenerator.buildPdfReportLayoutModel(
    COMPLETE_SUMMARY_DATA,
    "monthly",
    GENERATED_AT,
  );

  assert.equal(layoutModel.title, "Attendance Summary Report");
  assert.deepEqual(layoutModel.sections, [
    { key: "header", title: "Header" },
    { key: "executiveSummary", title: "Executive Summary" },
    { key: "statistics", title: "Statistics" },
    {
      key: "userAttendanceSummaryTable",
      title: "User Attendance Summary",
    },
    { key: "footer", title: "Footer" },
  ]);
  assert.equal(
    layoutModel.sections.some((section) => section.title === "Report Insight"),
    false,
  );
  assert.deepEqual(layoutModel.headerMetadata, [
    ["Period", "Monthly"],
    ["Generated on", reportGenerator.formatGeneratedOnCompact(GENERATED_AT)],
    ["Generated by", "Infinite Track System"],
    ["Data source", "/summary payload for selected report/export period"],
  ]);
  assert.deepEqual(
    layoutModel.executiveCards,
    reportGenerator.buildExecutiveSummaryCards(
      COMPLETE_SUMMARY_DATA.summary,
      COMPLETE_SUMMARY_DATA.report.data,
      COMPLETE_SUMMARY_DATA.analytics,
    ),
  );
  assert.deepEqual(
    layoutModel.statisticsCards,
    reportGenerator.buildPdfStatisticsCards(
      COMPLETE_SUMMARY_DATA.summary,
      COMPLETE_SUMMARY_DATA.report.data,
    ),
  );
  assert.deepEqual(layoutModel.tableColumns, EXPECTED_PDF_ATTENDANCE_COLUMNS);
  assert.deepEqual(layoutModel.tableHead, [
    EXPECTED_PDF_ATTENDANCE_COLUMNS.map((column) => column.header),
  ]);
  assert.equal(layoutModel.tableState, "ready");
  assert.equal(layoutModel.tableMessage, null);
  assert.deepEqual(
    layoutModel.tableBody,
    reportGenerator.buildPdfAttendanceTableRows(
      COMPLETE_SUMMARY_DATA.report.user_attendance_summary,
    ),
  );
  assert.deepEqual(layoutModel.footerTemplate, {
    left: "Generated by Infinite Track System",
    center: "Page {pageNumber}",
    right: "Confidential internal report",
  });
});

test("report generator builds workbook with only Summary, Attendance Report, and Discipline Insight sheets", () => {
  const workbook = reportGenerator.buildWorkbook(
    COMPLETE_SUMMARY_DATA,
    "monthly",
    GENERATED_AT,
  );

  assert.deepEqual(workbook.SheetNames, [
    "Summary",
    "Attendance Report",
    "Discipline Insight",
  ]);

  const summarySheet = workbook.Sheets.Summary;
  assert.equal(getSheetValue(summarySheet, "A1"), "Infinite Track Palu");
  assert.notEqual(getSheetValue(summarySheet, "A16"), "Honest Insight");

  const attendanceSheet = workbook.Sheets["Attendance Report"];
  assert.equal(getSheetValue(attendanceSheet, "A1"), "Full Name");
  assert.equal(getSheetValue(attendanceSheet, "E1"), "Attendance Date");
  assert.equal(getSheetValue(attendanceSheet, "N1"), "Discipline Label");
  assert.equal(getSheetValue(attendanceSheet, "O1"), "Location Description");

  const disciplineSheet = workbook.Sheets["Discipline Insight"];
  assert.equal(getSheetValue(disciplineSheet, "A1"), "Discipline Insight");
});

test("report generator does not expose out-of-scope fields as available workbook columns", () => {
  const rows = reportGenerator.buildAttendanceReportSheetRows(
    COMPLETE_SUMMARY_DATA.report.data,
  );

  assert.equal(rows[0].includes("Phone Number"), false);
  assert.equal(rows[1].includes("08123456789"), false);
});

test("report generator marks needs attention as unavailable/out-of-scope in executive cards", () => {
  const cards = reportGenerator.buildExecutiveSummaryCards(
    COMPLETE_SUMMARY_DATA.summary,
    COMPLETE_SUMMARY_DATA.report.data,
    COMPLETE_SUMMARY_DATA.analytics,
  );

  assert.equal(cards[3].label, "Needs Attention");
  assert.equal(cards[3].state, "backendRequired");
  assert.equal(cards[3].value, "Unavailable");
});

test("discipline insight sheet uses backend user_attendance_summary rows instead of raw report rows", () => {
  const rows = reportGenerator.buildDisciplineInsightSheetRows(
    COMPLETE_SUMMARY_DATA.report.user_attendance_summary,
    "monthly",
    GENERATED_AT,
  );

  assert.equal(rows[0][0], "Discipline Insight");
  assert.equal(rows[5][0], "Employee Name");
  assert.equal(rows[5][1], "Division");
  assert.equal(rows[5][2], "Attendance Rate");
  assert.equal(rows[6][0], "Rina Summary");
  assert.equal(rows[6][1], "Operations");
  assert.equal(rows[6][3], "2");
  assert.equal(rows[6][4], "0");
});

test("report generator builds the branded PDF document without weakening truthful export constraints", () => {
  const doc = reportGenerator.buildPdfDocument(
    COMPLETE_SUMMARY_DATA,
    "monthly",
    GENERATED_AT,
  );
  const pdfBytes = doc.output("arraybuffer");

  assert.ok(doc.getNumberOfPages() >= 1);
  assert.ok(pdfBytes.byteLength > 0);
});

test("report generator marks discipline insight as backend-required when user attendance summary rows are absent", () => {
  const rows = reportGenerator.buildDisciplineInsightSheetRows(
    [],
    "weekly",
    GENERATED_AT,
  );

  assert.deepEqual(rows, [
    ["Discipline Insight"],
    [""],
    ["Period", "Weekly"],
    ["Generated on", reportGenerator.formatGeneratedOn(GENERATED_AT)],
    [""],
    ["Availability", "Backend Required"],
    [
      "Insight Note",
      "Backend user_attendance_summary is unavailable for the selected period.",
    ],
  ]);
});

test("report generator keeps PDF summary fallbacks and Excel audit fallbacks truthful when row fields are missing", () => {
  const pdfRows = reportGenerator.buildPdfReportRows([
    {
      full_name: "Missing Fields",
      location_details: {},
    },
  ]);
  const excelRows = reportGenerator.buildExcelReportRows([
    {
      full_name: "Missing Fields",
      location_details: {},
    },
  ]);

  assert.equal(pdfRows[0][0], "Missing Fields");
  assert.equal(pdfRows[0][1], "Unavailable");
  assert.equal(pdfRows[0][2], "Unavailable");
  assert.equal(pdfRows[0][3], "Unavailable");
  assert.equal(pdfRows[0][7], "Unavailable");
  assert.equal(
    pdfRows[0][8],
    "Expected working days unavailable. Attendance coverage label unavailable.",
  );
  assert.equal(excelRows[0][12], "Unavailable");
  assert.equal(excelRows[0][13], "Unavailable");
  assert.equal(excelRows[0][14], "Unavailable");
});

test("report generator preserves explicit zero values in PDF summary counts and Excel audit discipline fields", () => {
  const pdfRows = reportGenerator.buildPdfReportRows([
    {
      full_name: "Explicit Zero",
      role_name: "Staff",
      division: "Operations",
      expected_working_days: 0,
      valid_attendance_days: 0,
      attendance_coverage_label: "0/0",
      on_time_days: 0,
      late_days: 0,
      alpha_days: 0,
      wfo_days: 0,
      wfh_days: 0,
      wfa_days: 0,
      latest_attendance_status: "alpha",
      latest_attendance_date: "2026-05-05",
      summary_note: "Backend returned explicit zero counts.",
    },
  ]);
  const excelRows = reportGenerator.buildExcelReportRows([
    {
      full_name: "Explicit Zero",
      discipline_score: 0,
      discipline_label: "0",
      location_details: {
        description: "Kantor Palu",
      },
    },
  ]);

  assert.equal(pdfRows[0][2], "0/0");
  assert.equal(pdfRows[0][3], "0");
  assert.equal(pdfRows[0][4], "0");
  assert.equal(pdfRows[0][5], "0");
  assert.equal(pdfRows[0][6], "WFO 0 • WFH 0 • WFA 0");
  assert.equal(pdfRows[0][7], "Alpha");
  assert.match(pdfRows[0][8], /Backend returned explicit zero counts\./);
  assert.equal(excelRows[0][12], "0");
  assert.equal(excelRows[0][13], "0");
  assert.equal(excelRows[0][14], "Kantor Palu");
});

test("report generator uses backend total metadata instead of row count as independent truth", () => {
  assert.equal(
    reportGenerator.formatReportTotalRecords({
      data: [{ attendance_id: "att_001" }],
      pagination: { total_records: "1" },
    }),
    "1",
  );
  assert.equal(
    reportGenerator.formatReportTotalRecords({
      data: [{ attendance_id: "att_001" }],
      pagination: { total_items: 1 },
    }),
    "1",
  );
  assert.equal(
    reportGenerator.formatReportTotalRecords({
      data: [{ attendance_id: "att_001" }],
    }),
    "Unavailable",
  );
});

test("report generator accepts explicit empty report arrays as valid export truth", () => {
  assert.deepEqual(
    reportGenerator.validateExportData(
      {
        summary: {},
        report: {
          data: [],
          pagination: {
            total_records: 0,
          },
        },
      },
      "PDF",
    ),
    [],
  );
});
